version: '2'
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
    - /Users/chrsalx/Documents/projects/personal/hack-day-2018/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: hackday
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
    - "3306:3306"
  main:
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - mysql
